article/urls.py
from django.urls import path
from .views import *
app_name = 'article'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('article/<int:pk>', ArticleDetail.as_view(), name='article'),
    path('article/create/', ArticleCreate.as_view(), name='create'),
    path('article/detail/<int:pk>', ArticleDetail.as_view(), name='detail'),
    path('article/update/<int:pk>', ArticleUpdate.as_view(), name='update'),
    path('article/delete/<int:pk>', ArticleDelete.as_view(), name='delete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('article.urls', 'article'), namespace='article')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('course/', include(('course.urls', 'course'), namespace='course')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='profile'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/update/', UserUpdateView.as_view(), name='update'),

]

article/models.py
from django.db import models
from user.models import User
from course.models import Column

# Create your models here.
class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    column = models.ForeignKey(Column, on_delete=models.CASCADE, null=True, blank=True,related_name='articles')
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

article/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.core.exceptions import PermissionDenied
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import ArticlePost,Comment
from django.contrib.auth.mixins import LoginRequiredMixin

class Index(ListView):
    template_name = 'article/index.html'
    queryset = ArticlePost.objects.all()
    paginate_by = 5
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created')
        query = self.request.GET.get('search')
        if query:
                    queryset = queryset.filter(
            Q(title__icontains=query) | Q(body__icontains=query) | Q(author__username__icontains=query)
        )

        
        return queryset

class ArticleDetail(DetailView):
    template_name = 'article/detail.html'
    context_object_name = 'article'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')  
        return ArticlePost.objects.get(pk=pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.get_object()
        comments = article.comments.all()  
        context['comments'] = comments
        return context
    

 
    def post(self, request, *args, **kwargs):
        article = self.get_object()  # 获取当前文章对象
        content = request.POST.get('content')  # 获取评论内容
        if not request.user.is_authenticated:
             return redirect('user:login')
        if content:
            comment = Comment(
                article=article,
                content=content,
                author=request.user  # 关联当前登录用户
                )
            comment.save()  # 保存评论
        return redirect('article:detail', pk=article.pk)  # 重定向回文章详情页面


class ArticleCreate(LoginRequiredMixin, CreateView):
    template_name = 'article/create.html'
    model = ArticlePost
    fields = ['title', 'body']
    success_url = '/'
    login_url = '/user/login/'

    def form_valid(self, form):
        # 自动将当前用户设置为作者
        form.instance.author = self.request.user
        return super().form_valid(form)

class ArticleUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'article/update.html'
    model = ArticlePost
    fields = ['title', 'body']
    success_url = '/'
    login_url = '/user/login/'

    def get_object(self, queryset=None):
        # 获取当前对象
        obj = super().get_object(queryset)
        # 确保当前用户是作者
        if obj.author != self.request.user:
            raise PermissionDenied("You do not have permission to edit this article.")
        return obj

class ArticleDelete(LoginRequiredMixin, DeleteView):
    model = ArticlePost
    success_url = '/'
    login_url = '/user/login/'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.author!= self.request.user:
            raise PermissionDenied("You do not have permission to delete this article.")
        return obj

templates/article/create.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <h1>Create New Article</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
</div>
{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">

    <!-- Article Content -->
    <div class="article-content">
        <header class="mb-3">
            <h1 class="text-primary">{{ article.title }}</h1>
            <small class="text-muted">Published on {{ article.created }}</small>
        </header>
        <section>
            <p>{{ article.body }}</p>
        </section>
        {% if user.id and article.author.id  %}
        <a href="{% url 'article:update' pk=article.id %}" class="btn btn-primary">修改文章</a>
        {% endif %}
        
    </div>

    <!-- Comments Section -->
    <div class="comments-section mt-4">
        <h3>Comments</h3>
        <hr>
        {% for comment in comments %}
        <div class="media mb-3">
            <div class="media-body">
                <h5 class="mt-0">{{ comment.author }}</h5>
                <p>{{ comment.content }}</p>
                <small class="text-muted">发表于{{ comment.created }}</small>
            </div>
        </div>
        {% empty %}
        <p>暂无评论</p>
        {% endfor %}
    </div>

    <!-- Comment Form -->
    <div class="comment-form mt-4">
        <form method="post">
            {% csrf_token %}
 
            <div class="form-group">
                <label for="content">评论</label>
                <textarea class="form-control" id="content" name="content" rows="3" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">发送</button>
        </form>
    </div>
</div>


{% endblock %}

templates/article/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row justify-content-center">
    {% if articles %}
    {% for article in articles %}
    <div class="card col-lg-8 mb-3">
      <div class="card-body">
        <div class="d-flex align-items-center mb-3">
          <img src="{{ article.author.avatar.url }}" alt="用户头像" class="rounded-circle me-3"
            style="width: 50px; height: 50px;">
          <div>
            <a href="{% url 'user:profile' article.author.id %}" class="text-decoration-none text-dark">
              <h6 class="mb-0">{{ article.author.username }}</h6>
            </a>
            <small class="text-muted">{{ article.created|timesince }}前</small>
          </div>
          <a href="{% url 'article:detail' article.id %}" class="ms-auto text-decoration-none text-dark fw-bold">原文</a>
        </div>
        <h3 class="card-title">{{article.title}}</h3>
        <p class="card-text">{{article.body|slice:":200"}}</p>


      </div>
    </div>
    {% endfor %}

    {% else %}
    <p class="text-center">目前没有文章。</p>
    {% endif %}
  </div>
</div>


{% if is_paginated %}
<nav aria-label="Pagination">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="/?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span> 上一页
      </a>
    </li>

    {% endif %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="/?page={{ page_obj.next_page_number }}" aria-label="Next">
        下一页 <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link" aria-hidden="true">下一页 &raquo;</span>
    </li>
    {% endif %}
  </ul>
  <div class="text-center mt-2">
    <span class="text-muted">
      第 <strong>{{ page_obj.number }}</strong> 页，共 <strong>{{ page_obj.paginator.num_pages }}</strong> 页。
    </span>
  </div>
</nav>
{% endif %}



{% endblock %}

templates/article/update.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <h1>Update Article</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
</div>
{% endblock %}